sudo: required

language: scala

jdk:
  - oraclejdk8
  - openjdk11

services:
  - docker

before_install:
  - docker pull amazon/dynamodb-local
  - docker run -d -p 8000:8000 amazon/dynamodb-local

script:
  - sbt test